### PR TITLE
Updated workflow

### PR DESCRIPTION
**Pull request by daprela**
This PR updates the webpack workflow.

* The list of packages has been updated
* Unused packages have been removed (still work to do)
* SCSS now is transpiled inside webpack. Gulp is not needed anymore for it

TODO
* remove SCSS compilation from Gulp
* See if it is possible to move more features from Gulp to Webpack

### CODE REVIEW

**Comment by Antisystems** [comment]
Por favor gulio devolverme la plata de taig soy Gabriel Eduardo Moya 542614687833

**Comment by daprela** [comment]
> Por favor gulio devolverme la plata de taig soy Gabriel Eduardo Moya 542614687833

No tengo idea de quién eres

**Comment by Antisystems** [comment]
Entonces alguien está suplantando su identidad en indonesia Michael Wahyudi
Dharmawan ***@***.*** Indonesia. En los documentos está su nombre
https://www.taig.cc/#/documents

**Comment by daprela** [comment]
I've never been to the US in my life, how can I be resident in Colorado?

**Pull request merged**
